# Generated by Django 4.1.7 on 2023-03-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Kody')),
                ('name', models.CharField(max_length=50, verbose_name='Ady')),
            ],
            options={
                'verbose_name_plural': 'Şäherler we Şäherçeler',
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Senesi')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='minimum temperatura')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='maximum temperatura')),
                ('unit', models.CharField(max_length=10, verbose_name='ölçeg birligi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='weather.city', verbose_name='Ýeri')),
            ],
            options={
                'verbose_name_plural': 'Gündelik Howa Maglumaty',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconPhrase', models.CharField(max_length=100, verbose_name='Gysgaça')),
                ('rain', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='ýagyş ähtimallygy')),
                ('snow', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='gar ähtimallygy')),
                ('ice', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='doňaklyk ähtimallygy')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Şemalyň tizligi')),
                ('wind_direction', models.CharField(max_length=10, verbose_name='Şemalyň ugry')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night', to='weather.dailyforecast', verbose_name='Senesi')),
            ],
            options={
                'verbose_name_plural': 'Gijesine',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconPhrase', models.CharField(max_length=100, verbose_name='Gysgaça')),
                ('rain', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='ýagyş ähtimallygy')),
                ('snow', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='gar ähtimallygy')),
                ('ice', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='doňaklyk ähtimallygy')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Şemalyň tizligi')),
                ('wind_direction', models.CharField(max_length=10, verbose_name='Şemalyň ugry')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='weather.dailyforecast', verbose_name='Senesi')),
            ],
            options={
                'verbose_name_plural': 'Gündizine',
            },
        ),
    ]
