# Generated by Django 4.1.7 on 2023-03-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='date',
            field=models.DateField(verbose_name='Senesi'),
        ),
    ]
