# Generated by Django 4.1.7 on 2023-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_dailyforecast_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='ice',
            field=models.IntegerField(verbose_name='doňaklyk ähtimallygy'),
        ),
        migrations.AlterField(
            model_name='day',
            name='rain',
            field=models.IntegerField(verbose_name='ýagyş ähtimallygy'),
        ),
        migrations.AlterField(
            model_name='day',
            name='snow',
            field=models.IntegerField(verbose_name='gar ähtimallygy'),
        ),
        migrations.AlterField(
            model_name='night',
            name='ice',
            field=models.IntegerField(verbose_name='doňaklyk ähtimallygy'),
        ),
        migrations.AlterField(
            model_name='night',
            name='rain',
            field=models.IntegerField(verbose_name='ýagyş ähtimallygy'),
        ),
        migrations.AlterField(
            model_name='night',
            name='snow',
            field=models.IntegerField(verbose_name='gar ähtimallygy'),
        ),
    ]
