# Generated by Django 4.1.7 on 2023-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_day_ice_alter_day_rain_alter_day_snow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyforecast',
            options={'verbose_name_plural': 'Gündelik Howa Maglumaty'},
        ),
        migrations.AddField(
            model_name='day',
            name='wind_unit',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Şemal tizliginiň ölçeg birligi'),
        ),
        migrations.AddField(
            model_name='night',
            name='wind_unit',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Şemal tizliginiň ölçeg birligi'),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Temperaturanyň ölçeg birligi'),
        ),
    ]
